const fs = require("fs");
const vm = require("vm");
global.window = global;
vm.runInThisContext(fs.readFileSync("assets/js/teamMapAnalysis.js", "utf8"));

let passed = 0;
function test(name, fn) { try { fn(); passed++; console.log(`PASS ${name}`); } catch (error) { console.error(`FAIL ${name}: ${error.message}`); process.exitCode = 1; } }
function assert(value, message) { if (!value) throw new Error(message); }
const types = TeamMapAnalysis.TYPES;
const person = (id, genius, frustration, competency) => ({ AssessmentResultID:id, FirstName:`Person${id}`, Genius1:genius[0], Genius2:genius[1], Frustration1:frustration[0], Frustration2:frustration[1], ...(competency ? {Competency1:competency[0],Competency2:competency[1]} : {}) });
const complement = (genius, frustration) => types.filter(type=>![...genius,...frustration].includes(type));
const make = (id, genius, frustration) => person(id,genius,frustration,complement(genius,frustration));
const metric = (distribution,type) => distribution.metrics.find(item=>item.type===type);

test("defaults normalize",()=>assert(TeamMapAnalysis.normalizeSettings({}).MaximumAutomaticObservations===8,"defaults missing"));
test("competencies derive from G and F",()=>{const row=person(1,["Wonder","Invention"],["Enablement","Tenacity"]);assert(TeamMapAnalysis.deriveParticipantCompetencies(row).join(",")==="Discernment,Galvanizing","derive failed");});
test("valid participant has 2G 2C 2F",()=>assert(TeamMapAnalysis.validateTeamMapAnalysisData([make(1,["Wonder","Invention"],["Enablement","Tenacity"])]).valid,"should validate"));
test("invalid overlapping placements are rejected",()=>assert(!TeamMapAnalysis.validateTeamMapAnalysisData([person(1,["Wonder","Wonder"],["Enablement","Tenacity"],["Invention","Discernment"])]).valid,"should reject"));
test("duplicates are rejected",()=>assert(!TeamMapAnalysis.validateTeamMapAnalysisData([make(1,["Wonder","Invention"],["Enablement","Tenacity"]),make(1,["Wonder","Invention"],["Enablement","Tenacity"])]).valid,"duplicate not rejected"));
const base=[make(1,["Wonder","Invention"],["Enablement","Tenacity"]),make(2,["Wonder","Discernment"],["Galvanizing","Tenacity"]),make(3,["Enablement","Tenacity"],["Wonder","Invention"]),make(4,["Galvanizing","Tenacity"],["Wonder","Discernment"])];
test("actual team size counts unique participants",()=>assert(TeamMapAnalysis.calculateTeamMapDistribution(base,"",{}).actualTeamSize===4,"wrong actual size"));
test("missing leader leaves denominator unweighted",()=>{const d=TeamMapAnalysis.calculateTeamMapDistribution(base,"missing",{});assert(d.weightedTeamSize===4&&!d.leaderWeightingApplied,"unexpected weighting");});
test("leader adds one Genius and Frustration influence point only",()=>{const d=TeamMapAnalysis.calculateTeamMapDistribution(base,"1",{});assert(d.weightedTeamSize===5,"wrong denominator");assert(metric(d,"Wonder").weightedGeniusCount===metric(d,"Wonder").actualGeniusCount+1,"G not weighted");assert(metric(d,"Enablement").weightedFrustrationCount===metric(d,"Enablement").actualFrustrationCount+1,"F not weighted");const geniusAdds=d.metrics.reduce((n,m)=>n+m.weightedGeniusCount-m.actualGeniusCount,0),frustrationAdds=d.metrics.reduce((n,m)=>n+m.weightedFrustrationCount-m.actualFrustrationCount,0);assert(geniusAdds===2&&frustrationAdds===2,"leader should add exactly 2G and 2F");});
test("leader weighting can be disabled",()=>assert(TeamMapAnalysis.calculateTeamMapDistribution(base,"1",{IncludeLeaderWeighting:false}).weightedTeamSize===4,"disable ignored"));
test("absent Genius is classified",()=>{const d=TeamMapAnalysis.calculateTeamMapDistribution(base,"",{});assert(metric(d,"Discernment").actualGeniusCount>0,"fixture wrong");const x=[make(1,["Wonder","Invention"],["Enablement","Tenacity"]),make(2,["Galvanizing","Tenacity"],["Wonder","Invention"])];const dx=TeamMapAnalysis.calculateTeamMapDistribution(x,"",{});assert(metric(dx,"Discernment").classifications.includes("Absent Genius"),"absent not classified");});
test("high frustration is classified",()=>{const d=TeamMapAnalysis.calculateTeamMapDistribution(base,"",{});assert(metric(d,"Wonder").classifications.some(x=>x.includes("Frustration")),"high F absent");});
test("competency-heavy is classified",()=>{const rows=[1,2,3].map(id=>make(id,["Wonder","Invention"],["Enablement","Tenacity"]));const d=TeamMapAnalysis.calculateTeamMapDistribution(rows,"",{});assert(metric(d,"Discernment").classifications.some(x=>x.includes("competency-heavy")),"competency-heavy absent");});
test("small team remains calculable",()=>{const d=TeamMapAnalysis.calculateTeamMapDistribution([base[0]],"",{});assert(d.validation.valid&&d.actualTeamSize===1,"small team failed");});
test("observation cap is honored",()=>{const d=TeamMapAnalysis.calculateTeamMapDistribution(base,"",{MaximumAutomaticObservations:2});assert(TeamMapAnalysis.generateTeamObservations(d).length<=2,"cap ignored");});
test("consultant questions can be disabled",()=>{const d=TeamMapAnalysis.calculateTeamMapDistribution(base,"",{IncludeConsultantQuestions:false});assert(TeamMapAnalysis.generateConsultantQuestions(d).length===0,"questions not disabled");});
test("suggestions are concise and identify the referenced Genius",()=>{const d=TeamMapAnalysis.calculateTeamMapDistribution(base,"1",{});const s=TeamMapAnalysis.suggestedAnalysis(d);assert(Object.keys(s).length===5&&!s.LeaderInfluence&&!s.Recommendations,"suggestions include removed fields");assert(/^(Wonder|Invention|Discernment|Galvanizing|Enablement|Tenacity):/.test(s.MostSignificantStrength)&&/^(Wonder|Invention|Discernment|Galvanizing|Enablement|Tenacity):/.test(s.MostSignificantRisk),"Genius reference missing");});
test("automatic language is cautious",()=>{const d=TeamMapAnalysis.calculateTeamMapDistribution(base,"1",{});const text=TeamMapAnalysis.generateTeamObservations(d).map(x=>x.text).join(" ");assert(/may|possible|suggest|could/i.test(text),"caution missing");});
test("admin inline scripts parse",()=>{const html=fs.readFileSync("admin/index.html","utf8");const scripts=[...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)].map(match=>match[1]).filter(Boolean);scripts.forEach(source=>new Function(source));assert(scripts.length>0,"no inline script found");});
test("Apps Script backend parses",()=>{new Function(fs.readFileSync("apps-script/Code.gs","utf8"));});
test("analysis persistence actions are wired",()=>{const backend=fs.readFileSync("apps-script/Code.gs","utf8"),transport=fs.readFileSync("assets/js/googleSheets.js","utf8");assert(backend.includes('action === "getTeamMapAnalysis"')&&backend.includes('action === "saveTeamMapAnalysis"')&&transport.includes("getTeamMapAnalysis")&&transport.includes("saveTeamMapAnalysis"),"persistence wiring missing");});
test("Team Map names use page-specific capacity and clipping protection",()=>{const html=fs.readFileSync("admin/index.html","utf8");assert(html.includes("--team-map-name-size:13px")&&html.includes("--team-map-name-size:9.5px")&&html.includes("font-weight:600")&&html.includes("const capacity=isConceptSheet?9:11")&&html.includes("firstColumnCapacity")&&html.includes("name.scrollWidth>name.clientWidth+1")&&html.includes("anyListOverflows()||anyNameClipsRight()")&&html.includes("requestAnimationFrame(fitTeamMapNames)"),"name fitting rules missing");});
test("global loading status and parallel startup are wired",()=>{const html=fs.readFileSync("admin/index.html","utf8"),transport=fs.readFileSync("assets/js/googleSheets.js","utf8"),loader=fs.readFileSync("assets/js/loadingStatus.js","utf8");new Function(loader);assert(html.includes("loadingStatus.js")&&html.includes("Promise.all([")&&html.includes('LoadingStatus.start("Loading JJC Admin", 8, "adminStartup")')&&transport.includes("requestStart(action)")&&loader.includes("About ${seconds(remaining)} sec remaining"),"loading progress wiring missing");});
test("analysis preview prints current edits and uses Team Map card order",()=>{const html=fs.readFileSync("admin/index.html","utf8");assert(!html.includes("if(teamMapAnalysisStale)return toast")&&html.includes("currentTeamMapAnalysis=analysisFromEditor();")&&html.includes("window.print();"),"preview print is still blocked");assert(html.includes('class="analysis-observation-grid"')&&html.includes("d.metrics.map(m =>")&&html.includes('Most Significant Contribution')&&html.includes('Primary Area to Explore'),"analysis layout missing");assert(!html.includes('<label>Leader Influence')&&!html.includes('<label>Recommendations'),"removed analysis fields still visible");});
test("analysis print page uses the simplified distribution table",()=>{const html=fs.readFileSync("admin/index.html","utf8");assert(html.includes('<th>Working Genius Type</th><th>Genius</th><th>Competency</th><th>Frustration</th>'),"simplified distribution columns missing");assert(html.includes('.team-map-analysis-sheet { box-sizing:border-box;')&&html.includes('height:11in !important'),"single-page print sizing missing");const active=html.slice(html.indexOf("renderTeamMapAnalysisPage = function"));assert(!active.includes('analysis-summary-grid')&&!active.includes('<th>Weighted G</th>')&&!active.includes('<th>Classification</th>'),"removed analysis summary data remains active");});
test("analysis PDF omits methodology to remain three pages",()=>{const html=fs.readFileSync("admin/index.html","utf8"),active=html.slice(html.indexOf("renderTeamMapAnalysisPage = function"));assert(active.includes("IncludeMethodologyNote:false"),"methodology is still enabled on the PDF analysis page");});
test("facilitator analysis selects at most one highlight per subject",()=>{const d=TeamMapAnalysis.calculateTeamMapDistribution(base,"1",{}),a=TeamMapAnalysis.generateFacilitatorAnalysis(d);assert(a.valid&&a.typeAnalyses.map(x=>x.type).join(",")===types.join(","),"six-type order incorrect");assert(a.stages.map(x=>x.label).join(",")==="Ideation,Activation,Implementation","stage analysis missing");assert(a.orientations.map(x=>x.label).join(",")==="Responsive,Disruptive","orientation analysis missing");assert(a.typeAnalyses.every(x=>x.highlights.length<=1)&&a.highlightGroups.stages.length<=3&&a.highlightGroups.orientations.length<=2,"duplicate subject highlight");assert(a.highlights.every(x=>["green","red","yellow"].includes(x.color)),"highlight color invalid");});
test("facilitator notes are grouped copy-ready and ordered",()=>{const d=TeamMapAnalysis.calculateTeamMapDistribution(base,"1",{}),text=TeamMapAnalysis.facilitatorNotesText(d,"LVCC"),highlightText=text.slice(text.indexOf("SUGGESTED HIGHLIGHTS"),text.indexOf("SIX WORKING GENIUSES"));assert(text.startsWith("LVCC — Team Map Facilitation Notes")&&highlightText.includes("Working Geniuses")&&highlightText.includes("Stages of Work")&&highlightText.includes("Responsive / Disruptive"),"highlight groups missing");assert(!highlightText.includes("%")&&/outline (Genius|Competency|Frustration) in (Green|Red|Yellow)/.test(highlightText),"highlight wording incorrect");assert(types.every((type,index)=>text.indexOf(`[${type[0]}] ${type.toUpperCase()}`)>0&&(index===0||text.indexOf(`[${types[index-1][0]}] ${types[index-1].toUpperCase()}`)<text.indexOf(`[${type[0]}] ${type.toUpperCase()}`))),"type notes out of order");assert(text.includes("Distribution:")&&text.includes("[IDEATION]")&&text.includes("[RESPONSIVE]"),"called-out labels or percentages missing");});
test("facilitator type distributions use one denominator and total 100",()=>{const d=TeamMapAnalysis.calculateTeamMapDistribution(base,"1",{}),a=TeamMapAnalysis.generateFacilitatorAnalysis(d);assert(a.typeAnalyses.every(item=>item.rates.genius+item.rates.competency+item.rates.frustration===100),"type distribution does not total 100");const tenacity=TeamMapAnalysis.normalizedInfluenceRates({weightedGeniusCount:10,actualCompetencyCount:6,weightedFrustrationCount:0});assert(tenacity.genius===63&&tenacity.competency===37&&tenacity.frustration===0,"leader-weighted normalization incorrect");});
test("zero Frustration never produces a red type highlight",()=>{const settings=TeamMapAnalysis.normalizeSettings({}),metrics=types.map(type=>({type,weightedGeniusCount:type==="Tenacity"?10:3,actualCompetencyCount:type==="Tenacity"?6:3,weightedFrustrationCount:type==="Tenacity"?0:3})),d={validation:{valid:true,errors:[]},settings,weightedTeamSize:15,metrics},a=TeamMapAnalysis.generateFacilitatorAnalysis(d),tenacity=a.typeAnalyses.find(item=>item.type==="Tenacity");assert(tenacity.rates.frustration===0&&!tenacity.highlights.some(item=>item.area==="Frustration"||item.color==="red"),"zero Frustration was highlighted red");});
test("orientation highlights require all three member types to share green, red, or yellow",()=>{const settings=TeamMapAnalysis.normalizeSettings({}),metric=(type,g,c,f)=>({type,weightedGeniusCount:g,actualCompetencyCount:c,weightedFrustrationCount:f}),allGreen={validation:{valid:true,errors:[]},settings,weightedTeamSize:12,metrics:[metric("Wonder",8,2,2),metric("Invention",4,4,4),metric("Discernment",8,2,2),metric("Galvanizing",4,4,4),metric("Enablement",8,2,2),metric("Tenacity",4,4,4)]},green=TeamMapAnalysis.generateFacilitatorAnalysis(allGreen);assert(green.highlightGroups.orientations.length===1&&green.highlightGroups.orientations[0].subject==="Responsive"&&green.highlightGroups.orientations[0].color==="green","unanimous green Responsive highlight missing");const mixed={...allGreen,metrics:allGreen.metrics.map(item=>item.type==="Enablement"?metric("Enablement",2,2,8):item)},mixedResult=TeamMapAnalysis.generateFacilitatorAnalysis(mixed);assert(!mixedResult.highlightGroups.orientations.some(item=>item.subject==="Responsive"),"mixed Responsive types should not create a highlight");const allRed={...allGreen,metrics:allGreen.metrics.map(item=>["Wonder","Discernment","Enablement"].includes(item.type)?metric(item.type,2,2,8):item)},red=TeamMapAnalysis.generateFacilitatorAnalysis(allRed);assert(red.highlightGroups.orientations.length===1&&red.highlightGroups.orientations[0].subject==="Responsive"&&red.highlightGroups.orientations[0].color==="red","unanimous red Responsive highlight missing");const allYellow={...allGreen,metrics:allGreen.metrics.map(item=>["Wonder","Discernment","Enablement"].includes(item.type)?metric(item.type,2,8,2):item)},yellow=TeamMapAnalysis.generateFacilitatorAnalysis(allYellow);assert(yellow.highlightGroups.orientations.length===1&&yellow.highlightGroups.orientations[0].subject==="Responsive"&&yellow.highlightGroups.orientations[0].color==="yellow"&&yellow.highlightGroups.orientations[0].area==="Competency","unanimous yellow Responsive highlight missing");});
test("LVCC aggregate highlights only dominant Implementation",()=>{const genius=[22,13,22,9,61,74],competency=[59,23,55,18,23,23],frustration=[17,65,26,70,17,4],d={validation:{valid:true,errors:[]},settings:TeamMapAnalysis.normalizeSettings({}),weightedTeamSize:100,metrics:types.map((type,index)=>({type,weightedGeniusRate:genius[index],weightedGeniusCount:genius[index],actualCompetencyRate:competency[index],weightedFrustrationRate:frustration[index],weightedFrustrationCount:frustration[index]}))},a=TeamMapAnalysis.generateFacilitatorAnalysis(d);assert(a.highlightGroups.stages.length===1&&a.highlightGroups.stages[0].subject==="Implementation"&&a.highlightGroups.stages[0].area==="Genius","incorrect stage highlight");assert(a.highlightGroups.orientations.length===0,"orientation should not be highlighted");});
test("workshop and group actions expose slide notes and PNG downloads",()=>{const html=fs.readFileSync("admin/index.html","utf8"),library=fs.readFileSync("assets/js/assessmentLibrary.js","utf8");new Function(library);assert(html.includes("openWorkshopFacilitatorAnalysis")&&html.includes("downloadWorkshopCondensedTeamMap")&&library.includes("openAssessmentGroupFacilitatorAnalysis")&&library.includes("downloadAssessmentGroupCondensedMap"),"workshop or group actions missing");assert(html.includes("condensedTeamMapPngBlob")&&html.includes("canvas.toBlob")&&html.includes("Condensed Team Map.png"),"standalone PNG export missing");});
test("condensed PNG headers center the letter and type as one measured group",()=>{const html=fs.readFileSync("admin/index.html","utf8");assert(html.includes("context.measureText(card.type).width")&&html.includes("const headerGroupWidth=badgeDiameter+headerGap+")&&html.includes("const badgeCenterX=headerStart+badgeDiameter/2")&&html.includes('context.textAlign="left"; context.fillText(card.type,headerStart+badgeDiameter+headerGap'),"condensed header alignment missing");});
test("condensed PNG Genius and Frustration subheaders restore centered alignment",()=>{const html=fs.readFileSync("admin/index.html","utf8");assert(html.includes('context.font="800 22px Montserrat, Arial, sans-serif"; context.textAlign="center"; context.fillStyle="#15803d"; context.fillText("Genius"'),"condensed subheaders are not explicitly centered");});
test("browser print filenames use record context",()=>{const html=fs.readFileSync("admin/index.html","utf8");assert(html.includes("printWithContextName")&&html.includes("- Assessment Results")&&html.includes("- Team Map")&&html.includes("currentPrintFileName = `${documentSubject} - ${type}`"),"contextual print names missing");});

console.log(`${passed} Team Map analysis tests passed.`);
